EC-EduCheck/edu_check

- README.md
> [EC-9] chore: 허스키 설정

- api/src/main/java/org/example/educheck/domain/member/entity/Member.java
- api/src/main/java/org/example/educheck/global/security/config/SecurityConfig.java
> [EC-13] BE/chore: 시큐리티 수정  

- client/src/components/buttons/mainButton/MainButton.jsx
- client/src/components/buttons/mainButton/MainButton.module.css
- EC-17
- MainButton 공통 스타일 변경
> [EC-17] FE/feat: MainButton 공통 스타일 변경

- client/src/components/buttons/roundButton/RoundButton.jsx
- client/src/components/buttons/roundButton/RoundButton.module.css
- EC-20
- RoundButton 공통 스타일 수정
> [EC-20] FE/feat: round button 공통 스타일 설정

- client/src/components/buttons/mainButton/MainButton.jsx
- client/src/components/buttons/mainButton/MainButton.module.css
- client/src/components/sideBar/SideBar.jsx
- client/src/css/index.css
- client/src/utils/buttonContentList.js
- EC-22
- MainButton title prop에따른 배경색 및 크기 자동 설정 기능 구현
> [EC-22] feat/refactor: MainButton title prop에따른 배경색 및 크기 자동 설정 기능 구현

- client/src/components/buttons/roundButton/RoundButton.jsx
- client/src/components/buttons/roundButton/RoundButton.module.css
- client/src/pages/dashBoard/DashBoard.jsx
- client/src/utils/buttonContentList.js
- EC-23
- style: buttonContent title 내용 추가
- refactor: RoundButton 스타일 수정 및 기능 주석 처리
> [EC-23] FE/refactor: 버튼 공통 스타일 구현

- api/src/main/java/org/example/educheck/domain/attendance/entity/Attendance.java
- api/src/main/java/org/example/educheck/domain/consulting/entity/Consulting.java
- api/src/main/java/org/example/educheck/domain/member/entity/Member.java
- api/src/main/java/org/example/educheck/domain/member/staff/entity/Staff.java
- api/src/main/java/org/example/educheck/domain/member/student/entity/Student.java
- api/src/main/java/org/example/educheck/domain/registration/entity/Registration.java
- EC-27
- ENUM 대신 VARCHAR로 저장하도록 변경
> [EC-27] refactor/Enum type DB 저장시 String 저장

- api/src/main/java/org/example/educheck/global/common/config/RedisConfig.java
> [EC-29] BE/chore:  redis config 설정

- api/src/main/java/org/example/educheck/domain/member/controller/AuthController.java
- api/src/main/java/org/example/educheck/global/common/exception/ErrorCode.java
- api/src/main/java/org/example/educheck/global/common/exception/GlobalException.java
- api/src/main/java/org/example/educheck/global/common/exception/custom/LoginValidationException.java
- api/src/main/java/org/example/educheck/global/common/exception/custom/ResourceNotFoundException.java
- api/src/main/java/org/example/educheck/global/common/exception/handler/GlobalExceptionHandler.java
- EC-33
- 예외 처리 공통화 구현
- ErrorCode의 에러 코드값은 오전 데일리 스크럼 시간에 논의해보아요.
> [EC-33] BE/feat: 예외 처리 공통화

- api/src/main/java/org/example/educheck/global/security/jwt/JwtTokenUtil.java
- EC-34
payload에 데이터 들어가지 않던 문제 수정
> [EC-34] fix: 토큰 claims 부분 수정

- api/src/main/java/org/example/educheck/domain/member/controller/AuthController.java
- api/src/main/java/org/example/educheck/domain/member/dto/EmailCheckResponseDto.java
- api/src/main/java/org/example/educheck/domain/member/service/AuthService.java
- EC-35
- 회원가입 시 사용할 메일 중복 검사 기능 구현
> [EC-35] feat: 메일 중복 검사 기능 구현

- .github/workflows/deploy.yml
- api/Dockerfile
- client/Dockerfile
- client/nginx.conf
- client/templates/default.conf.template
- client/templates/https.conf.template
- docker-compose.yml
- EC-41
- 배포 설정
- env file 문서 추가
> [EC-41] BE/chore: 배포 설정

- api/src/main/java/org/example/educheck/domain/meetingroomreservation/service/MeetingRoomReservationService.java
- api/src/main/java/org/example/educheck/global/common/exception/ErrorCode.java
- api/src/main/java/org/example/educheck/global/common/exception/custom/common/GlobalException.java
- api/src/main/java/org/example/educheck/global/common/exception/custom/common/ResourceNotFoundException.java
- api/src/main/java/org/example/educheck/global/common/exception/custom/reservation/ReservationConflictException.java
- api/src/main/java/org/example/educheck/global/common/exception/handler/GlobalExceptionHandler.java
- EC-38
- 에러처리 공통화 구조 결정 사항 반영
> [EC-38] BE/chore: 에러처리 공통화 구조

- api/src/main/java/org/example/educheck/domain/attendance/controller/AttendanceController.java
- api/src/main/java/org/example/educheck/domain/attendance/dto/request/AttendanceUpdateRequestDto.java
- api/src/main/java/org/example/educheck/domain/attendance/dto/response/AttendanceListResponseDto.java
- api/src/main/java/org/example/educheck/domain/attendance/dto/response/AttendanceResponseDto.java
- api/src/main/java/org/example/educheck/domain/attendance/dto/response/StudentAttendanceListResponseDto.java
- api/src/main/java/org/example/educheck/domain/attendance/dto/response/StudentAttendanceResponseDto.java
- api/src/main/java/org/example/educheck/domain/attendance/entity/Attendance.java
- api/src/main/java/org/example/educheck/domain/attendance/repository/AttendanceRepository.java
- api/src/main/java/org/example/educheck/domain/attendance/service/AttendanceService.java
- api/src/main/java/org/example/educheck/domain/lecture/repository/LectureRepository.java
- api/src/main/java/org/example/educheck/domain/member/repository/StaffRepository.java
- api/src/main/java/org/example/educheck/domain/member/staff/entity/Staff.java
- api/src/main/java/org/example/educheck/domain/staffcourse/repository/StaffCourseRepository.java
- EC-39
- 관리자의 수강생 금일 출결 현황 조회 구현
- 관리자의 수강생 세부 출결 현황 조회 구현
> [EC-39] FE/feat: 관리자 - 출결 기능 구현

- api/src/main/java/org/example/educheck/domain/member/controller/AuthController.java
- api/src/main/java/org/example/educheck/domain/member/dto/RefreshTokenRotateResponseDto.java
- api/src/main/java/org/example/educheck/domain/member/entity/Member.java
- api/src/main/java/org/example/educheck/domain/member/service/AuthService.java
- api/src/main/java/org/example/educheck/global/security/config/SecurityConfig.java
- api/src/main/java/org/example/educheck/global/security/jwt/JwtTokenUtil.java
- EC-43
- 로그인 시 리프레시 토큰 추가 발급 기능
- 리프레시 토큰 로테이션 구현
- 액세스 토큰 재발급 시 응답 데이터 추가
> [EC-43] BE/feat 로그인 리프레시 토큰

- client/src/pages/login/Login.jsx
- client/src/pages/login/Login.module.css
> [EC-26] FE/feat: 로그인 기능 구현

- client/src/pages/dashBoard/DashBoard.jsx
- client/src/pages/roomReservation/RoomReservation.jsx
- client/src/pages/roomReservation/RoomReservation.module.css
- client/src/pages/roomReservation/hourBlock/HourBlock.jsx
- client/src/pages/roomReservation/hourBlock/HourBlock.module.css
- client/src/pages/roomReservation/timeGrid/TimeGrid.jsx
- client/src/pages/roomReservation/timeGrid/TimeGrid.module.css
- client/src/pages/roomReservation/timeSlot/TimeSlot.jsx
- client/src/pages/roomReservation/timeSlot/TimeSlot.module.css
> [EC-40] FE/feat 예약 전체 현황 조회 페이지 UI 구현

- api/src/main/java/org/example/educheck/domain/attendance/service/AttendanceService.java
- EC-47
- 관리자의 출석 exception 처리 수정
> [EC-47] BE/refactor: 관리자의 출석 exception 처리 수정

- api/src/main/java/org/example/educheck/domain/attendance/repository/AttendanceRepository.java
- api/src/main/java/org/example/educheck/domain/lecture/Lecture.java
> [EC-49] fix: 쿼리 수정

- client/src/components/buttons/closeButton/CloseButton.jsx
- client/src/components/buttons/moreButton/MoreButton.jsx
- client/src/components/sideBar/SideBar.jsx
- client/src/components/sideBar/sidebarItemIcon/SidebarItemIcon.jsx
- client/src/components/tab/Tab.jsx
- client/src/pages/dashBoard/DashBoard.jsx
- client/src/pages/login/Login.jsx
- client/src/pages/staffAttendance/StaffAttendance.jsx
- client/src/pages/staffAttendanceAbsence/StaffAttendanceAbsence.jsx
- client/src/pages/staffAttendanceDetail/StaffAttendanceDetail.jsx
- client/src/pages/staffRoomReservation/StaffRoomReservation.jsx
- client/src/pages/staffStudentManage/StaffStudentManage.jsx
- client/src/pages/studentAttendance/StudentAttendance.jsx
- client/src/pages/studentAttendanceAbsence/StudentAttendanceAbsence.jsx
- client/src/pages/studentSetting/StudentSetting.jsx
- client/src/router/index.jsx
- client/src/store/slices/authSlice.js
- client/src/utils/dashBoardList.js
- client/src/utils/sideBarList.js
- client/src/utils/tabContentList.js
- EC-48
- feat: router index 경로 구현
- feat: 사용자 role에 따른 sidebaritemicon 전환 기능
- feat: SideBarItem 사용자에 따른 내용 및 기능 수정
- feat: 사용자 권한에 따른 DashBoard 기능 구현
- feat: 사용자 권한에 따른 Tab 기능 구현
- style: 코드 정렬
> [EC-48] FE/feat: 사용자 권한에 따른 기능 구현

- client/src/pages/home/Home.jsx
> [EC-54] fix: 로그인 상태에 따른 라우트구조

- client/src/router/index.jsx
> [EC-56] FE/refactor: 페이지 import 삭제

- client/src/pages/login/Login.jsx
- client/src/store/slices/authSlice.js
- client/src/store/slices/sideBarItemSlice.js
- EC-57
- 사용자 권한에 따른 사이드바 자동화 추가
> [EC-57] FE/refactor: 사용자 권한에 따른 사이드바 자동화 추가

- api/src/main/java/org/example/educheck/domain/member/service/AuthService.java
- api/src/main/java/org/example/educheck/global/common/exception/ErrorCode.java
- api/src/main/java/org/example/educheck/global/common/exception/custom/LoginValidationException.java
- api/src/main/java/org/example/educheck/global/common/exception/handler/GlobalExceptionHandler.java
- EC-55
- 로그인 예외 처리를 ErrorCode ENUM을 사용하도록 리팩토링
> [EC-55] refactor: 로그인 예외처리 ENUM 사용

- api/src/main/java/org/example/educheck/global/common/exception/ErrorCode.java
- EC-59
- ErrorCode 에서 , 누락 수정
> [EC-59] BE/fix: ErrorCode 에서 , 누락 수정

- api/src/main/java/org/example/educheck/domain/meetingroomreservation/controller/MeetingRoomReservationController.java
- api/src/main/java/org/example/educheck/domain/meetingroomreservation/dto/response/MeetingRoomReservationResponseDto.java
- api/src/main/java/org/example/educheck/domain/meetingroomreservation/repository/MeetingRoomReservationRepository.java
- api/src/main/java/org/example/educheck/domain/meetingroomreservation/service/MeetingRoomReservationService.java
- api/src/main/java/org/example/educheck/domain/member/entity/Member.java
- api/src/main/java/org/example/educheck/domain/member/student/entity/Student.java
- EC-60
- 특정 회의실 예약 내역 상세 조회 API 구현
> [EC-60] BE/feat: 회의실 예약 내역 상세 조회 api

- api/src/main/java/org/example/educheck/domain/meetingroomreservation/controller/MeetingRoomReservationController.java
- api/src/main/java/org/example/educheck/domain/meetingroomreservation/dto/response/CampusMeetingRoomsDto.java
- api/src/main/java/org/example/educheck/domain/meetingroomreservation/dto/response/MeetingRoomDto.java
- api/src/main/java/org/example/educheck/domain/meetingroomreservation/dto/response/MeetingRoomReservationResponseDto.java
- api/src/main/java/org/example/educheck/domain/meetingroomreservation/dto/response/MeetingRoomReservationsProjections.java
- api/src/main/java/org/example/educheck/domain/meetingroomreservation/dto/response/ReservationDto.java
- api/src/main/java/org/example/educheck/domain/meetingroomreservation/repository/MeetingRoomReservationRepository.java
- api/src/main/java/org/example/educheck/domain/meetingroomreservation/service/MeetingRoomReservationService.java
- EC-66
- 캠퍼스 내 회의실 예약 내역 전체 조회 API
> [EC-66] BE/feat 회의실 예약 내역 전체 조회 api

- api/src/main/java/org/example/educheck/domain/meetingroomreservation/repository/MeetingRoomReservationRepository.java
- api/src/main/java/org/example/educheck/domain/meetingroomreservation/service/MeetingRoomReservationService.java
- api/src/main/java/org/example/educheck/global/common/exception/custom/common/InvalidRequestException.java
- EC-67
- 회의실 예약시 하루 2시간 내외 예약 가능 유효성 검증
> [EC-67] BE/feat: 회의실 예약시 하루 2시간 내외 가능 유효성 검증

- api/src/main/java/org/example/educheck/domain/attendance/controller/AttendanceController.java
- api/src/main/java/org/example/educheck/domain/attendance/repository/AttendanceRepository.java
- api/src/main/java/org/example/educheck/domain/attendance/service/AttendanceService.java
- EC-65
- 퇴실 api 구현
```
{
    "message": "출석 성공",
    "code": "OK",
    "data": {
        "status": "ATTENDANCE"
    }
}
```
```
{
    "message": "출석 성공",
    "code": "OK",
    "data": {
        "status": "EARLY_LEAVE"
    }
}
```
> [EC-65] BE/feat: 퇴실 api 구현

- client/src/api/attendanceApi.js
- client/src/components/sideBar/SideBar.jsx
> [EC-68] BE/feat:퇴실 api 연동

- client/src/components/sideBar/SideBar.jsx
- EC-69
- 배포 테스트를 위한 불필요한 코드 제거
> [EC-69] refactor: 불필요한 코드 제거

- api/src/main/java/org/example/educheck/domain/attendance/controller/AttendanceController.java
- api/src/main/java/org/example/educheck/domain/attendance/service/AttendanceService.java
- EC-71
- 퇴실 api 위치정보 받아오도록 수정
- 지각처리 부분 수정
- 출석/ 중복 출석 에러 처리
> [EC-71] BE/refactor: 퇴실 api 리펙토링

- api/src/main/java/org/example/educheck/global/security/config/SecurityConfig.java
- client/src/App.jsx
- client/src/api/authApi.js
- client/src/main.jsx
- client/src/pages/login/Login.jsx
- EC- 70
- FE 리프레시 토큰 API 연동
- BE 해당 API 인증 제외 경로 추가
> [EC-70] FE/feat: 리프레시 토큰 API 연동

- api/src/main/java/org/example/educheck/domain/member/controller/AuthController.java
- api/src/main/java/org/example/educheck/domain/member/service/AuthService.java
> [EC-73] feat: 로그아웃 기능 구현

- client/src/pages/studentSetting/StudentSetting.jsx
> [EC-45] FE/feat: 개인정보 수정 유효성 검사

- client/src/App.jsx
- EC-78
- 임시 처리
- JWT 예외 처리 후 진행 예정
> [EC-78] BE/chore: 액세스 토큰 재발급 api 연동 수정

- client/src/components/progressBar/ProgressBar.jsx
- client/src/components/progressBar/ProgressBar.module.css
- EC-79
- 진행률에 따라 변화하는 div Bar 구현
```
<ProgressBar 
value={50} 
max={100} 
startDate="2025-01-01" 
endDate="2025-03-24" 
/>
```
```
<ProgressBar 
value={value} 
max={100} 
startDate={startDate} 
endDate={endDate}
/>
```
> [EC-79] FE/feat: 진행률 BAR 컴포넌트 구현

- api/src/main/java/org/example/educheck/global/security/config/SecurityConfig.java
- api/src/main/java/org/example/educheck/global/security/config/SecurityPathConfig.java
- EC-76
- 인증 관련 Public URL 별도 파일로 분리
> [EC-76] BE/refactor: 인증 관련 Public URL 별도 파일로 분리

- client/src/components/inputBox/InputBox2/InputBox2.jsx
- client/src/components/inputBox/InputBox2/InputBox2.module.css
- client/src/components/inputBox/InputBox3/InputBox3.jsx
- client/src/components/inputBox/InputBox3/InputBox3.module.css
- client/src/pages/studentAttendanceAbsence/StudentAttendanceAbsence.jsx
- client/src/pages/studentAttendanceAbsence/StudentAttendanceAbsence.module.css
> [EC-77] FE/feat: 유고 결석 페이지 UI 구현

- api/src/main/java/org/example/educheck/domain/member/repository/MemberRepository.java
- api/src/main/java/org/example/educheck/domain/member/service/AuthService.java
- EC-85
- 권한에 따라 로그인 로직 변경
- 관리자 캠퍼스, 강좌 정보 반환하도록 수정
> [EC-85] fix: 관리자 로그인 수정

- api/src/main/java/org/example/educheck/domain/member/entity/Member.java
- api/src/main/java/org/example/educheck/domain/member/staff/entity/Staff.java
- api/src/main/java/org/example/educheck/domain/member/student/entity/Student.java
- Member가 주체가 되도록 변경
- EC-86
- Member, Student, Staff 연관관계 관리 주체 변경
> [EC-86] BE/refactor: Member, Student, Staff 연관관계 관리 주체 변경

- client/src/components/calendar/calendar.module.css
- EC-89
- 캘린더 width, height %로 변경
> [EC-89] FE/refactor: 캘린더 스타일 변경

- api/src/main/java/org/example/educheck/domain/absenceattendance/controller/AbsenceAttendanceController.java
- api/src/main/java/org/example/educheck/domain/absenceattendance/service/AbsenceAttendanceService.java
- EC-81
- 권한 체크 추가
- 엔드 포인트 수정
- 엔드포인트에  `course/{courseId}` 추가하였습니다.
기존
`
/api/my/absence-attendances
`
변경
`
/api/my/course/{courseId}/absence-attendances
`
> [EC-91] feat: 엔드 포인트 권한 체크 추가

- client/src/pages/studentAttendance/StudentAttendance.jsx
- client/src/pages/studentAttendance/StudentAttendance.module.css
- EC-92
- 지각, 조퇴, 결석 indicator 추가
> [EC-92] FE/feat: 출결 Indicator 추가

- client/src/components/calendar/calendar.jsx
- client/src/pages/studentAttendance/StudentAttendance.jsx
- EC-${NUMBER}
- calendar 에서 Calendar로 변경
- 파일명 변경에 따른 StudentAttendance 페이지 내의 Calendar import 경로 변경
> [EC-95] FE/refactor: 캘린더 컴포넌트 파일명 변경

- client/src/components/listItem/baseListItem/BaseListItem.jsx
- client/src/components/listItem/baseListItem/BaseListItem.module.css
- client/src/components/tag/Tag.jsx
- client/src/pages/staffStudentManage/StaffStudentManage.jsx
> [EC-84] FE/feat: 과정 관리자 학습자 관리 UI 구현

- client/src/components/dashBoardItem/DashBoardItem.jsx
- client/src/pages/staffRoomReservation/StaffRoomReservation.jsx
- client/src/pages/staffRoomReservation/StaffRoomReservation.module.css
> [EC-98] FE/feat: 과정 관리자 회의실 예약 UI 구현

- client/src/components/sideBar/SideBar.jsx
- client/src/components/sideBar/SideBar.module.css
- client/src/pages/login/Login.module.css
- client/src/pages/studentSetting/StudentSetting.module.css
- EC-101
- 사이드바 높이 수정
- 로그인 ui 중앙 정렬
- 개인정보 수정 중앙 정렬
> [EC-101] FE/refactor : 공통 스타일 수정

- api/src/main/java/org/example/educheck/domain/member/service/AuthService.java
- EC-104
- 관리자 refresh 응답 바디 수정
> [EC-104]  fix: 리프레시 로직 수정

- client/src/components/dashBoardItem/DashBoardItem.jsx
- client/src/components/dataBoard/DataBoard.module.css
- client/src/pages/studentAttendance/StudentAttendance.jsx
- client/src/pages/studentAttendance/StudentAttendance.module.css
> [EC-105] FE/refactor : 공통 컴포넌트 수정

- api/src/main/java/org/example/educheck/domain/absenceattendance/controller/AbsenceAttendanceController.java
- api/src/main/java/org/example/educheck/domain/absenceattendance/dto/response/UpdateAbsenceAttendacneReponseDto.java
- api/src/main/java/org/example/educheck/domain/absenceattendance/service/AbsenceAttendanceService.java
- EC-107
- 응답 형태 API 명세서에 맞춰 구조화
> [EC-107] feat: 응답 형태 수정

- api/src/main/java/org/example/educheck/global/common/exception/custom/common/GlobalException.java
- api/src/main/java/org/example/educheck/global/common/exception/handler/GlobalExceptionHandler.java
- EC-108
- 예외 메세지 커스텀 예외 적용 되도록 해결
> [EC-108] feat: 예외 메세지 커스텀 예외 적용 되도록 해결

- api/src/main/java/org/example/educheck/global/common/exception/ErrorCode.java
- api/src/main/java/org/example/educheck/global/common/exception/handler/GlobalExceptionHandler.java
- EC-109
- 첨부파일 업로드 사이즈 초과시 예외 처리 및 응답 메세지
> [EC-109] feat: 첨부파일 업로드 사이즈 초과 예외 처리

- client/src/pages/staffStudentManage/StaffStudentManage.jsx
- client/src/pages/staffStudentManage/StaffStudentManage.module.css
- EC-99
- 과정관리자 학습자관리 학습자등록 UI 구현
> [EC-99] FE/feat: 과정관리자 학습자관리 학습자등록 UI 구현

- api/src/main/java/org/example/educheck/domain/absenceattendance/dto/response/GetAbsenceAttendancesResponseDto.java
> [EC-114] feat: 유고결석 전체 조회 api 변경

- client/src/components/tag/Tag.jsx
- client/src/pages/staffStudentManage/StaffStudentManage.jsx
> [EC-113] feat: 관리자 학습자관리 페이지 리펙토링

- api/src/main/java/org/example/educheck/domain/absenceattendance/controller/AbsenceAttendanceController.java
- api/src/main/java/org/example/educheck/domain/attendance/controller/AttendanceController.java
- api/src/main/java/org/example/educheck/domain/attendance/dto/response/MyAttendanceListResponseDto.java
- api/src/main/java/org/example/educheck/domain/attendance/dto/response/MyAttendanceResponseDto.java
- api/src/main/java/org/example/educheck/domain/attendance/service/AttendanceService.java
- api/src/main/java/org/example/educheck/domain/registration/repository/RegistrationRepository.java
- api/src/main/java/org/example/educheck/domain/studentCourseAttendance/entity/StudentCourseAttendance.java
- api/src/main/java/org/example/educheck/domain/studentCourseAttendance/entity/StudentCourseAttendanceId.java
- api/src/main/java/org/example/educheck/domain/studentCourseAttendance/repository/StudentCourseAttendanceRepository.java
- EC-106
- 출석부 확인 요청시 유효성 검증
- 존재하는 과정인지
- 학습자가 해당 과정을 수강 하는지
- 요청 날짜에 대한 검증
- 응답 구조화 및 API 구현
- 페이지네이션 및 쿼리파라미터를 통한 월별 필터링 아직 미구현 상태입니다.
-
> [EC-106] BE/feat: 학습자 출석부 기록 api

- client/src/pages/staffAttendance/StaffAttendance.jsx
- client/src/pages/staffAttendance/StaffAttendance.module.css
> [EC-103] FE/feat: 관리자 금일 출석 현황 기능 구현

- api/src/main/java/org/example/educheck/domain/staffcourse/repository/StaffCourseRepository.java
- api/src/main/java/org/example/educheck/domain/studentCourseAttendance/controller/StudentCourseAttendanceController.java
- api/src/main/java/org/example/educheck/domain/studentCourseAttendance/service/StudentCourseAttendanceService.java
- EC-${NUMBER}
- 예외 처리
- 관리자가 해당 교육 과정 관리자인지
- 수강생이 해당 교육 과정 수강중인지
- 존재하는 수강생인지
- 해당 교육 과정이 존재하는지
> [EC-121] BE/feat: 관리자 수강생 전체 출석 기록 조회 API 예외 처리

- api/src/main/java/org/example/educheck/domain/attendance/dto/response/AttendanceListResponseDto.java
- api/src/main/java/org/example/educheck/domain/attendance/dto/response/AttendanceResponseDto.java
- api/src/main/java/org/example/educheck/domain/attendance/service/AttendanceService.java
- api/src/main/java/org/example/educheck/domain/member/student/repository/StudentRepository.java
- client/src/components/modal/Modal.jsx
- client/src/components/modal/Modal.module.css
- client/src/pages/staffAttendance/StaffAttendance.jsx
- EC-120
- 관리자의 금일 출석 현황 API 수정
- students API 연동
- 에러 발생 시 모달 창 구현
> [EC-120] FE/feat : 관리자 금일 출석 기능 구현

- api/src/main/java/org/example/educheck/domain/attendance/controller/AttendanceController.java
- api/src/main/java/org/example/educheck/domain/attendance/dto/response/MyAttendanceRecordListResponseDto.java
- api/src/main/java/org/example/educheck/domain/attendance/dto/response/MyAttendanceRecordResponseDto.java
- api/src/main/java/org/example/educheck/domain/attendance/service/AttendanceService.java
- api/src/main/java/org/example/educheck/domain/studentCourseAttendance/controller/StudentCourseAttendanceController.java
- api/src/main/java/org/example/educheck/domain/studentCourseAttendance/repository/StudentCourseAttendanceRepository.java
- api/src/main/java/org/example/educheck/domain/studentCourseAttendance/service/StudentCourseAttendanceService.java
- EC-122
- 학습자 출석부 기록 조회 API 페이징 처리 및 예외 처리
- AttendanceController에서 별도로 분리
- 출석 관련 타 기능이 많아 분리했습니다.
- 월별에 대한 쿼리파라미터를 통한 필터링 (달력에서 필요)
> [EC-122] BE/feat: 학습자 출석부 기록 조회 API 페이징 처리 및 예외 처리

- api/src/main/java/org/example/educheck/domain/attendance/service/AttendanceService.java
> [EC-124] fix: import 문 누락 수정

- client/src/components/buttons/dropBoxButton/DropBoxButton.jsx
- client/src/components/listItem/baseListItem/BaseListItem.jsx
- client/src/components/tag/Tag.jsx
- client/src/pages/staffStudentManage/StaffStudentManage.jsx
- EC-117
- 관리자 학습자 관리 드롭다운 버튼 클릭 변경
- DropBoxButton, BaseListItem, Tag  로직 변경
> [EC-117] FE/feat: 관리자 학습자 관리 드롭다운 버튼 클릭 변경

- client/src/pages/staffStudentManage/StaffStudentManage.jsx
- EC-112
- 과정관리자 학습자관리 학습자등록 버튼 클릭 시 모달 적용
> [EC-112] FE/feat: 과정관리자 학습자관리 학습자등록 모달 적용

- client/src/components/infoItem/InfoItem.module.css
- client/src/pages/staffRoomReservation/StaffRoomReservation.jsx
- client/src/pages/staffRoomReservation/StaffRoomReservation.module.css
- EC-111
- 과정 관리자 회의실 예약 상세 모달창 UI 구현
> [EC-111] FE/feat: 과정 관리자 회의실 예약 상세 UI 구현

- api/src/main/java/org/example/educheck/domain/absenceattendance/dto/response/GetAbsenceAttendancesResponseDto.java
- EC-133
- 코스 유고결석 전체 조회 응답 바디 absenceAttendanceId 추가
> [EC-133] feat: 코스 유고결석 전체 조회 응답 바디 absenceAttendanceId 추가

- api/src/main/java/org/example/educheck/domain/studentCourseAttendance/dto/response/AttendanceStatsResponseDto.java
- api/src/main/java/org/example/educheck/domain/studentCourseAttendance/repository/StudentCourseAttendanceRepository.java
- api/src/main/java/org/example/educheck/domain/studentCourseAttendance/service/StudentCourseAttendanceService.java
- EC-134
- 해당 과정에 수강중인 학생인지 유효성 검증 추가
- 응답 데이터에서 중복 필드 제거
> [EC-134] feat: 해당 과정에 수강중인 학생인지 유효성 체크

- api/src/main/java/org/example/educheck/domain/absenceattendance/controller/AbsenceAttendanceController.java
- api/src/main/java/org/example/educheck/domain/absenceattendance/dto/request/CreateAbsenceAttendacneRequestDto.java
- api/src/main/java/org/example/educheck/domain/absenceattendance/dto/request/UpdateAbsenceAttendacneRequestDto.java
- api/src/main/java/org/example/educheck/domain/absenceattendance/dto/response/CreateAbsenceAttendanceResponseDto.java
- api/src/main/java/org/example/educheck/domain/absenceattendance/dto/response/UpdateAbsenceAttendacneReponseDto.java
- api/src/main/java/org/example/educheck/domain/absenceattendance/service/AbsenceAttendanceService.java
> [EC-138] fix: 필드 오타 수정

- api/src/main/java/org/example/educheck/domain/absenceattendance/service/AbsenceAttendanceService.java
> [EC-141] fix: 오타 수정

- client/src/pages/staffAttendanceAbsence/StaffAttendanceAbsence.jsx
> [EC-142] FE/fix: 누락 수정

- client/src/components/buttons/moreButton/MoreButton.module.css
- client/src/components/listItem/leftLineListItem/LeftLineListItem.jsx
- client/src/components/listItem/leftLineListItem/LeftLineListItem.module.css
- client/src/pages/studentAttendanceAbsence/StudentAttendanceAbsence.jsx
> [EC-146] FE/feat : 학습자 유고결석 UI 구현

- client/src/components/sideBar/SideBar.jsx
- client/src/components/sideBar/sidebarItem/SidebarItem.jsx
- client/src/components/tab/Tab.jsx
- client/src/components/tab/tabButton/TabButton.jsx
> [EC-147] FE/feat : 공통 컴포넌트 수정

- api/src/main/java/org/example/educheck/domain/studentCourseAttendance/controller/StudentCourseAttendanceController.java
- EC-150
- 관리자 특정 학생 출결 세부 사항 API default size 수정
> [EC-150] refactor: 관리자 특정 학생 출결 세부 사항 API default size 수정

- client/index.html
- client/public/assets/favicon_io/site.webmanifest
- client/src/pages/staffAttendance/StaffAttendance.jsx
- EC-148
- api response에 따른 수정
> [EC-148] FE/refactor: 관리자 출결 수정

- client/src/css/index.css
- client/src/pages/staffAttendance/StaffAttendance.jsx
> [EC-151] FE/feat : 사이드바 수정

- client/src/components/buttons/circleButton/CircleButton.module.css
- client/src/components/listItem/baseListItem/BaseListItem.module.css
- client/src/components/listItem/leftLineListItem/LeftLineListItem.jsx
- client/src/components/listItem/leftLineListItem/LeftLineListItem.module.css
- client/src/components/modal/Modal.module.css
- client/src/components/tab/Tab.jsx
- client/src/pages/staffAttendance/StaffAttendance.jsx
- client/src/pages/staffAttendance/StaffAttendance.module.css
- client/src/pages/staffAttendanceAbsence/StaffAttendanceAbsence.jsx
- client/src/pages/staffAttendanceAbsence/StaffAttendanceAbsence.module.css
- client/src/pages/staffAttendanceDetail/StaffAttendanceDetail.module.css
- client/src/pages/staffStudentManage/StaffStudentManage.jsx
- client/src/pages/staffStudentManage/StaffStudentManage.module.css
> [EC-152] FE/feat : 공통 스타일 수정

- api/src/main/java/org/example/educheck/domain/absenceattendance/service/AbsenceAttendanceService.java
- api/src/main/java/org/example/educheck/global/common/s3/S3Service.java
- EC-144
- 다중 첨부 파일 업로드시 S3에 마지막 파일이 n번 업로드되는 문제 해결
> [EC-144] BE/fix: 유고 결석 신청시 다중 첨부 파일 업로드시 문제 해결

- client/src/components/dashBoardItem/DashBoardItem.module.css
- client/src/components/inputBox/newInputBox/NewInputBox.module.css
- client/src/components/listItem/leftLineListItem/LeftLineListItem.module.css
- client/src/pages/studentAttendanceAbsence/StudentAttendanceAbsence.jsx
- client/src/pages/studentAttendanceAbsence/StudentAttendanceAbsence.module.css
- EC-139
- 학습자 유고결석 페이지 리팩토링
- LeftLineListIem 수정, NewInputBox 수정, DashBoardItem 수정
- 신청 버튼 클릭 시 비동기 작업
- map 사용해서 페이지 리팩토링
> [EC-139] FE/refactor: 학습자 유고결석 페이지 리팩토링

- client/src/pages/studentAttendanceAbsence/StudentAttendanceAbsence.jsx
- client/src/pages/studentAttendanceAbsence/StudentAttendanceAbsence.module.css
> [EC-155] FE/feat: 학습자 유고결석 모달 구현

- client/src/pages/roomReservation/RoomReservation.jsx
> [EC-163] test: 테스트 배포

- client/src/pages/roomReservation/RoomReservation.jsx
> [EC-164] test: 테스트 배포

- client/src/pages/roomReservation/RoomReservation.jsx
> [EC-165] test: 테스트 배포

- client/package-lock.json
- client/package.json
- client/src/pages/roomReservation/RoomReservation.jsx
> [EC-166] test: 테스트 배포

- client/Dockerfile
> [EC-167] test: 테스트 배포

- .github/workflows/deploy.yml
> [EC-168] test: 테스트 배포

- .github/workflows/deploy.yml
> [EC-169] test: 테스트 배포

- .github/workflows/deploy.yml
> [EC-170] test: 테스트 배포

- .github/workflows/deploy.yml
> [EC-171] test: 테스트 배포

- .github/workflows/deploy.yml
> [EC-172] test: 테스트 배포

- docker-compose.yml
> [EC-173] test: 테스트 배포

- .github/workflows/deploy.yml
> [EC-174] test: 테스트 배포

- .github/workflows/deploy.yml
- client/src/pages/roomReservation/RoomReservation.jsx
> [EC-175] FE/test : 에러 확인

- .github/workflows/deploy.yml
- client/src/pages/roomReservation/RoomReservation.jsx
- client/src/router/index.jsx
- docker-compose.yml
> [EC-177] FE/test : 에러 확인

- client/src/components/modal/Modal.module.css
- client/src/router/index.jsx
> [EC-178] FE/style: 관리자 유고결석

- api/src/main/java/org/example/educheck/domain/lecture/repository/LectureRepository.java
- api/src/main/java/org/example/educheck/domain/studentCourseAttendance/dto/response/AttendanceStatsProjection.java
- api/src/main/java/org/example/educheck/domain/studentCourseAttendance/dto/response/AttendanceStatsResponseDto.java
- api/src/main/java/org/example/educheck/domain/studentCourseAttendance/repository/StudentCourseAttendanceRepository.java
- api/src/main/java/org/example/educheck/domain/studentCourseAttendance/service/StudentCourseAttendanceService.java
- EC-181
- 출석 상태에 유고 결석 승인 상태 반영
- 쿼리 로직 변경
> [EC-181] refactor/feat: 수강생 출석 관련 통계 데이터 조회 api 유고결석 인정 반영

- api/src/main/resources/application.properties
- EC-${NUMBER}
- 회원가입 페이지 구현
- 노드 추가 패키지 설치
> [EC-191] chore: 날짜 설정

- api/src/main/java/org/example/educheck/domain/attendance/entity/Attendance.java
- client/src/api/attendanceApi.js
- client/src/pages/Test.jsx
- client/src/router/index.jsx
- EC-183
- axios 설정
- 리버스 프록시 설정
> [EC-183] FE/feat 출석부 다운로드 api 연동

- client/src/components/modal/Modal.jsx
- client/src/components/modal/Modal.module.css
- client/src/css/index.css
- client/src/pages/roomReservation/RoomReservation.jsx
- client/src/pages/roomReservation/RoomReservation.module.css
> [EC-192] feat: 회의실 예약 모달 기능 추가

- app/app.py
- EC-194
- 출석부 json/excel 플라스크 서버
.env 업데이트
> [EC-194] feat: json 모듈 변경

- client/src/components/inputBox/newInputBox/NewInputBox.module.css
- client/src/components/listItem/leftLineListItem/LeftLineListItem.module.css
- client/src/css/index.css
- EC-193
- LeftList css 수정
- NewInput css 수정
- index.css  에러 코드 제거
> [EC-193] FE/refactor: css 변경

- api/Dockerfile
- api/src/main/java/org/example/educheck/domain/meetingroomreservation/service/MeetingRoomReservationService.java
- api/src/main/resources/application.properties
- docker-compose.yml
- EC-197
- 배포 환경 시간 설정
- 백엔드 Dockerfile 중복 제거
> [EC-197] DE/chore: 배포 환경 시간 설정

- client/package-lock.json
- client/package.json
- client/src/components/inputBox/newInputBox/NewInputBox.jsx
- client/src/pages/studentAttendanceAbsence/StudentAttendanceAbsence.jsx
- client/src/pages/studentAttendanceAbsence/StudentAttendanceAbsence.module.css
- EC-195
- react-datePicker 추가
- NewInputBox 컴포넌트에 ref 속성 추가
- 제출시 file 초기화를 위한 ref 속성 추가
-  학습자 유고 결석 페이지 수정
- 노드 추가 패키지 설치
> [EC-195] FE/feat: 학습자 유고 결석 페이지 수정

- api/src/main/java/org/example/educheck/domain/member/repository/StaffRepository.java
- api/src/main/java/org/example/educheck/domain/member/staff/controller/StaffController.java
- api/src/main/java/org/example/educheck/domain/member/staff/service/StaffService.java
- api/src/main/java/org/example/educheck/domain/member/student/dto/response/StudentInfoResponseDto.java
- api/src/main/java/org/example/educheck/domain/registration/repository/RegistrationRepository.java
- client/src/api/studentManageApi.js
- client/src/pages/staffStudentManage/StaffStudentManage.jsx
- EC-201
- 관리자 관리 교육 과정 수강생 전체 조회 API 연동 (학습자 관리 페이지)
- API 조회 및 유효성 검증 쿼리 최적화
> [EC-201] FE/feat: 관리자 수강생 전체 조회 api 연동

- client/src/api/attendanceApi.js
> [EC-202] fix: 소실된 코드 복구

- api/src/main/java/org/example/educheck/domain/member/controller/MyController.java
- api/src/main/java/org/example/educheck/domain/member/dto/response/MyProfileResponseDto.java
- api/src/main/java/org/example/educheck/domain/member/repository/MemberRepository.java
- api/src/main/java/org/example/educheck/domain/member/service/MyService.java
- client/src/api/profileApi.js
- client/src/pages/studentSetting/StudentSetting.jsx
- EC-${NUMBER}
- 회원가입 페이지 구현
- 노드 추가 패키지 설치
> Feat/ec 205 be 개인 정보 조회 api

- client/package-lock.json
- client/package.json
- client/vite.config.js
- EC-206
- gzip 압축 설정
- 패키지 설치 있습니다.
> [EC-206] chore: gzip 압축 최적화 설정

- api/src/main/java/org/example/educheck/domain/studentCourseAttendance/controller/StudentCourseAttendanceController.java
- api/src/main/java/org/example/educheck/domain/studentCourseAttendance/dto/response/AttendanceRateStatisticsDto.java
- api/src/main/java/org/example/educheck/domain/studentCourseAttendance/dto/response/AttendanceRateStatisticsProjection.java
- api/src/main/java/org/example/educheck/domain/studentCourseAttendance/dto/response/AttendanceRecordListResponseDto.java
- api/src/main/java/org/example/educheck/domain/studentCourseAttendance/dto/response/AttendanceStatisticsResponseDto.java
- api/src/main/java/org/example/educheck/domain/studentCourseAttendance/repository/StudentCourseAttendanceRepository.java
- api/src/main/java/org/example/educheck/domain/studentCourseAttendance/service/StudentCourseAttendanceService.java
- EC-207
- 금일 기준 출석률, 전체 출석률, 과정 진행률 데이터 추가
- 해당 데이터 조회하기 위한 DTO 및 쿼리 추가
> [ EC-207] BE/feat: 관리자 세부 출결 현황에서 진행률 조회 관련 추가

- api/src/main/resources/application.properties
> [EC-208] DE/chore: grale build 최적화 설정

- client/src/pages/staffAttendanceDetail/StaffAttendanceDetail.jsx
- EC-${NUMBER}
- 회원가입 페이지 구현
- 노드 추가 패키지 설치
> [EC-209] feat: 세부 출결 현황 API 연동

- client/src/components/inputBox/InputBox.jsx
- client/src/pages/studentSetting/StudentSetting.jsx
- EC-214
- API 순서 보장
- 페이지 들어왔을 때 생년월일, 핸드폰번호 초기값
> [EC-214] feat: 순서 보장 및 초기 데이터

- api/src/main/java/org/example/educheck/domain/meetingroomreservation/service/MeetingRoomReservationService.java
- client/src/pages/roomReservation/RoomReservation.jsx
- client/src/store/slices/authSlice.js
- EC-216
- 회의실 예약 예약 시간 이전인지 예외 처리
- 예약 색상 회의실별 고정 -> 랜덤으로 변경
> [EC-216] FE/feat, style: 회의실 예약 예외 처리 추가 및 예약 색상 랜덤으로 변경

- api/src/main/java/org/example/educheck/domain/member/controller/MyController.java
- api/src/main/java/org/example/educheck/domain/member/dto/EditMyProfileRequestDto.java
- api/src/main/java/org/example/educheck/domain/member/dto/UpdateMyProfileRequestDto.java
- api/src/main/java/org/example/educheck/domain/member/dto/response/EmailCheckResponseDto.java
- api/src/main/java/org/example/educheck/domain/member/dto/response/LoginResponseDto.java
- api/src/main/java/org/example/educheck/domain/member/dto/response/RefreshTokenRotateResponseDto.java
- api/src/main/java/org/example/educheck/domain/member/entity/Member.java
- api/src/main/java/org/example/educheck/domain/member/repository/MemberRepository.java
- api/src/main/java/org/example/educheck/domain/member/service/AuthService.java
- api/src/main/java/org/example/educheck/domain/member/service/MyService.java
- EC-215
- 회원 정보 수정 API
- Date / DateTime 타입 변경
> [EC-215] feat: 회원정보 수정 API 구현

- client/src/pages/login/Login.jsx
> [EC-219] feat: 로그인 화면 폼 추가

- api/src/main/java/org/example/educheck/domain/member/controller/AuthController.java
- api/src/main/java/org/example/educheck/domain/member/dto/response/RegisteredMemberResponseDto.java
- api/src/main/java/org/example/educheck/domain/member/service/AuthService.java
- client/package-lock.json
- client/src/api/holidayApi.js
- client/src/api/studentManageApi.js
- client/src/pages/login/Login.jsx
- client/src/pages/staffAttendance/StaffAttendance.jsx
- client/src/pages/staffAttendance/StaffAttendance.module.css
- client/src/pages/staffStudentManage/StaffStudentManage.jsx
- EC-${NUMBER}
- 회원가입 페이지 구현
- 노드 추가 패키지 설치
> Feat/ec 217 fe 관리자 학습자 등록 api 연동

- client/src/components/buttons/dropBoxButton/DropBoxButton.jsx
- client/src/components/buttons/moreButton/MoreButton.jsx
- client/src/components/listItem/leftLineListItem/LeftLineListItem.jsx
- client/src/pages/studentAttendanceAbsence/StudentAttendanceAbsence.jsx
- client/src/pages/studentAttendanceAbsence/StudentAttendanceAbsence.module.css
- EC-${NUMBER}
- 유고 결석 수정 모달 구현
- LeftLineListItem onclick 추가
- 수정 클릭과 삭제 클릭 추가
- MoreButton onClick 속성 추가
- DropButton onClick 속성 수정
> [EC-212] FE/refactor:유고 결석 신청 수정 관련 변경

- api/src/main/java/org/example/educheck/domain/absenceattendance/controller/AbsenceAttendanceController.java
- api/src/main/java/org/example/educheck/domain/absenceattendance/repository/AbsenceAttendanceRepository.java
- client/src/api/absenceAttendancesApi.js
- client/src/components/inputBox/newInputBox/NewInputBox.jsx
- client/src/pages/studentAttendanceAbsence/StudentAttendanceAbsence.jsx
> [EC-224] FE/feat: 관리자 유고 결석 api 연동

- client/src/api/absenceAttendancesApi.js
- client/src/pages/studentAttendanceAbsence/StudentAttendanceAbsence.jsx
- EC-225
- 유고 결석 신청 내역 삭제 api 연동
> [EC-225] FE/feat: 수강생 유고 결석 내역 삭제 api 연동

- client/src/pages/staffStudentManage/StaffStudentManage.jsx
- EC-227
- 관리자 학습자 관리 페이지 생년월일 수정
> [EC-227] FE/feat: 관리자 학습자 관리 페이지 생년월일 수정

- api/src/main/java/org/example/educheck/domain/member/staff/controller/StaffController.java
- api/src/main/java/org/example/educheck/domain/member/staff/dto/request/UpdateStudentRegistrationStatusRequestDto.java
- api/src/main/java/org/example/educheck/domain/member/staff/service/StaffService.java
- app/app.py
- client/src/api/instance/apiInstance.js
- client/src/api/studentManageApi.js
- client/src/components/listItem/baseListItem/BaseListItem.jsx
- client/src/components/tag/Tag.jsx
- client/src/pages/staffStudentManage/StaffStudentManage.jsx
- EC-223
- 수강생 상태 변경 API 연동
- 수강생 상태 변경 API
-  PUT -> PATCH 변경
> [EC-223] FE/feat: 수강생 상태 변경 페이지 + API HTTP METHOD 변경

- .github/workflows/deploy.yml
- api/src/main/java/org/example/educheck/domain/absenceattendance/controller/AbsenceAttendanceController.java
- api/src/main/java/org/example/educheck/domain/attendance/service/AttendanceService.java
- api/src/main/java/org/example/educheck/domain/meetingroomreservation/service/MeetingRoomReservationService.java
- client/src/components/modal/Modal.module.css
- client/src/pages/studentAttendanceAbsence/StudentAttendanceAbsence.jsx
- client/src/pages/studentAttendanceAbsence/StudentAttendanceAbsence.module.css
- EC-222
- BE 예약 가능한 잔여 시간 예외 메세지 포함
- BE 시간 계산 로직 수정
- BE 거리 계산 임시
- FE 예약 화면 모달 background 수정
> [EC-222] BE/refactor 리팩토링 및 예외처리

- client/src/components/sideBar/SideBar.jsx
- client/src/pages/home/Home.jsx
- client/src/pages/login/Login.jsx
- client/src/pages/roomReservation/RoomReservation.jsx
- client/src/pages/staffAttendanceDetail/StaffAttendanceDetail.jsx
- client/src/pages/staffStudentManage/StaffStudentManage.jsx
- client/src/pages/staffStudentManage/StaffStudentManage.module.css
- client/src/pages/studentAttendanceAbsence/StudentAttendanceAbsence.jsx
- client/src/pages/studentSetting/StudentSetting.jsx
- EC-232
주석 정리 및 관리자 학습자 관리 페이지 여백 조정
> [EC-232] style: 주석 정리 및 관리자 학습자 관리 페이지 여백 조정

- client/src/pages/studentSetting/StudentSetting.module.css
> [EC-190] FE/refactor: 개인정보 수정 페이지 리팩토링

- api/src/main/java/org/example/educheck/domain/absenceattendance/controller/AbsenceAttendanceController.java
- client/src/components/listItem/leftLineListItem/LeftLineListItem.jsx
- client/src/pages/studentAttendanceAbsence/StudentAttendanceAbsence.jsx
- EC-235
- 수강생 유고 결석 상세 조회 기능 구현
> [EC-235] feat: 수강생 유고 결석 상세 조회

- api/src/main/java/org/example/educheck/domain/absenceattendance/repository/AbsenceAttendanceRepository.java
- api/src/main/java/org/example/educheck/domain/absenceattendance/service/AbsenceAttendanceService.java
- api/src/main/java/org/example/educheck/domain/studentCourseAttendance/service/StudentCourseAttendanceService.java
- api/src/main/java/org/example/educheck/global/common/exception/custom/common/InvalidRequestException.java
- client/src/css/index.css
- client/src/pages/staffStudentManage/StaffStudentManage.jsx
- client/src/pages/studentAttendanceAbsence/StudentAttendanceAbsence.jsx
- client/src/pages/studentAttendanceAbsence/StudentAttendanceAbsence.module.css
- EC-234
- FE input 박스 폰트 적용 및 버튼 이동
- FE 예외 처리
- BE 유고 결석 신청 관련 예외 처리
> [EC-234 FE/refactor 마무리 수정

- api/src/main/java/org/example/educheck/domain/member/service/AuthService.java
- api/src/main/java/org/example/educheck/domain/member/service/MyService.java
- api/src/main/java/org/example/educheck/global/common/exception/ErrorCode.java
- api/src/main/java/org/example/educheck/global/common/exception/custom/auth/EmailNotFoundException.java
- api/src/main/java/org/example/educheck/global/common/exception/handler/GlobalExceptionHandler.java
- api/src/main/java/org/example/educheck/global/security/CustomUserDetailsService.java
- api/src/main/java/org/example/educheck/global/security/config/SecurityConfig.java
- api/src/main/java/org/example/educheck/global/security/jwt/JwtTokenUtil.java
- EC-236
- 로그인 로직 중 불필요한 db조회 제거
- 리플렉션 코드 제거
- 예외처리 추가
> [EC-236] feat: 로그인 성능 개선

- api/src/main/java/org/example/educheck/domain/member/service/AuthService.java
- api/src/main/java/org/example/educheck/domain/member/service/MyService.java
- EC-237
- 학습자 등록 시 상태값 PREVIOUS->PROGRESS
> [EC-237] BE/feat: 학습자 등록 시 상태값 변경
